EXE_NAME_GAME_CLIENT := neotetris

SRC_DIR_GAME_CLIENT := src
HEADERS_DIR_GAME_CLIENT := include

SRC_GAME_CLIENT := $(shell find $(SRC_DIR_GAME_CLIENT)/ -name "*.cpp")
HEADERS_GAME_CLIENT := $(shell find $(HEADERS_DIR_GAME_CLIENT) -name "*.hpp")

CXX = g++

COMPILER_FLAGS_GAME_CLIENT := -I$(HEADERS_DIR_GAME_CLIENT)
LINKER_FLAGS_GAME_CLIENT := -lSDL2 -lvulkan -ldl -lpthread -lX11
# LINKER_FLAGS_GAME_CLIENT := -lSDL2 -lvulkan -ldl -lpthread -lX11 -lXxf86vm -lXrandr -lXi

$(EXE_NAME_GAME_CLIENT): $(SRC_GAME_CLIENT) $(HEADERS_GAME_CLIENT)
	$(CXX) $(SRC_GAME_CLIENT) $(COMPILER_FLAGS_GAME_CLIENT) $(LINKER_FLAGS_GAME_CLIENT) -o $@
